const { neon } = require("@neondatabase/serverless");
const crypto = require("node:crypto");

require("dotenv/config");
const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is required");
}

const sql = neon(databaseUrl);

const RECIPES = [
  {
    id: 1,
    name: "Classic Pancakes",
    ingredients: [
      "2 cups all-purpose flour",
      "2 tbsp sugar",
      "2 tsp baking powder",
      "1/2 tsp salt",
      "1 1/2 cups milk",
      "1 egg",
      "2 tbsp melted butter",
      "1 tsp vanilla extract",
    ],
    tags: ["Breakfast", "Vegetarian", "Easy"],
    shortDescription: "Fluffy homemade pancakes perfect for breakfast.",
    rating: 4.8,
    prepTimeMinutes: 20,
    servings: 4,
    calorie: 320,
    protein: 8,
    carbs: 45,
    fats: 11,
    thumbnail: "https://images.unsplash.com/photo-1528207776546-365bb710ee93",
    instructions: [
      "Mix dry ingredients together.",
      "Whisk wet ingredients separately.",
      "Combine wet and dry ingredients until just mixed.",
      "Cook on a greased skillet until golden on both sides.",
      "Serve warm with syrup.",
    ],
  },
  {
    id: 2,
    name: "Grilled Chicken Salad",
    thumbnail: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
    ingredients: [
      "2 chicken breasts",
      "4 cups mixed greens",
      "1 cucumber",
      "1 tomato",
      "1 avocado",
      "2 tbsp olive oil",
      "1 tbsp lemon juice",
      "Salt",
      "Black pepper",
    ],
    tags: ["Lunch", "High Protein", "Healthy", "Gluten-Free"],
    shortDescription: "Fresh salad topped with juicy grilled chicken.",
    rating: 4.7,
    prepTimeMinutes: 30,
    servings: 2,
    calorie: 410,
    protein: 38,
    carbs: 12,
    fats: 24,
    instructions: [
      "Season and grill the chicken.",
      "Chop vegetables.",
      "Slice cooked chicken.",
      "Mix vegetables and dressing.",
      "Top with grilled chicken and serve.",
    ],
  },
  {
    id: 3,
    name: "Spaghetti Bolognese",
    thumbnail:
      "https://plus.unsplash.com/premium_photo-1664472619078-9db415ebef44",
    ingredients: [
      "250g spaghetti",
      "300g ground beef",
      "1 onion",
      "2 garlic cloves",
      "2 cups tomato sauce",
      "1 tbsp olive oil",
      "Italian seasoning",
      "Salt",
      "Parmesan cheese",
    ],
    tags: ["Dinner", "Italian", "Comfort Food"],
    shortDescription: "Traditional Italian pasta with rich meat sauce.",
    rating: 4.9,
    prepTimeMinutes: 45,
    servings: 4,
    calorie: 580,
    protein: 29,
    carbs: 58,
    fats: 22,
    instructions: [
      "Cook spaghetti according to package instructions.",
      "Sauté onion and garlic.",
      "Brown ground beef.",
      "Add tomato sauce and seasonings.",
      "Simmer for 20 minutes.",
      "Serve sauce over spaghetti with Parmesan.",
    ],
  },
  {
    id: 4,
    name: "Vegetable Stir Fry",
    thumbnail:
      "https://plus.unsplash.com/premium_photo-1664478238082-3df93e48c491",
    ingredients: [
      "Broccoli",
      "Bell pepper",
      "Carrot",
      "Snap peas",
      "Soy sauce",
      "Garlic",
      "Ginger",
      "Sesame oil",
    ],
    tags: ["Dinner", "Vegan", "Quick"],
    shortDescription: "Colorful vegetables stir-fried in a savory sauce.",
    rating: 4.6,
    prepTimeMinutes: 20,
    servings: 3,
    calorie: 240,
    protein: 7,
    carbs: 25,
    fats: 12,
    instructions: [
      "Heat sesame oil.",
      "Cook garlic and ginger.",
      "Add vegetables and stir fry.",
      "Pour in soy sauce.",
      "Cook until vegetables are tender-crisp.",
    ],
  },
  {
    id: 5,
    name: "Chocolate Chip Cookies",
    thumbnail: "https://images.unsplash.com/photo-1597733153203-a54d0fbc47de",
    ingredients: [
      "2 cups flour",
      "1 cup butter",
      "3/4 cup sugar",
      "3/4 cup brown sugar",
      "1 egg",
      "1 tsp vanilla",
      "1 tsp baking soda",
      "1 cup chocolate chips",
    ],
    tags: ["Dessert", "Baking", "Snack"],
    shortDescription: "Soft and chewy chocolate chip cookies.",
    rating: 4.9,
    prepTimeMinutes: 30,
    servings: 24,
    calorie: 180,
    protein: 2,
    carbs: 24,
    fats: 9,
    instructions: [
      "Cream butter and sugars.",
      "Mix in egg and vanilla.",
      "Add dry ingredients.",
      "Fold in chocolate chips.",
      "Bake at 350°F (175°C) for 10-12 minutes.",
    ],
  },
  {
    id: 6,
    name: "Chicken Fried Rice",
    thumbnail: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
    ingredients: [
      "3 cups cooked rice",
      "200g chicken breast",
      "2 eggs",
      "Frozen peas and carrots",
      "Soy sauce",
      "Green onions",
      "Sesame oil",
    ],
    tags: ["Dinner", "Asian", "One-Pan"],
    shortDescription: "Quick and flavorful homemade chicken fried rice.",
    rating: 4.8,
    prepTimeMinutes: 25,
    servings: 4,
    calorie: 470,
    protein: 27,
    carbs: 45,
    fats: 18,
    instructions: [
      "Cook chicken and set aside.",
      "Scramble eggs.",
      "Stir fry vegetables.",
      "Add rice and soy sauce.",
      "Mix in chicken and eggs.",
      "Garnish with green onions.",
    ],
  },
  {
    id: 7,
    name: "Greek Yogurt Parfait",
    thumbnail: "https://images.unsplash.com/photo-1550594645-25c5bd703258",
    ingredients: [
      "2 cups Greek yogurt",
      "1 cup granola",
      "1 cup mixed berries",
      "2 tbsp honey",
    ],
    tags: ["Breakfast", "Healthy", "High Protein", "No Cook"],
    shortDescription: "Creamy yogurt layered with berries and crunchy granola.",
    rating: 4.5,
    prepTimeMinutes: 10,
    servings: 2,
    calorie: 290,
    protein: 18,
    carbs: 32,
    fats: 9,
    instructions: [
      "Layer yogurt in serving glasses.",
      "Add granola.",
      "Top with berries.",
      "Drizzle with honey and serve.",
    ],
  },
  {
    id: 8,
    name: "Margherita Pizza",
    thumbnail: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
    ingredients: [
      "1 pizza dough",
      "1/2 cup pizza sauce",
      "200g fresh mozzarella",
      "Fresh basil leaves",
      "2 tbsp olive oil",
      "Salt",
      "Black pepper",
    ],
    tags: ["Dinner", "Italian", "Vegetarian", "Baking"],
    shortDescription:
      "A classic Italian pizza topped with fresh mozzarella and basil.",
    rating: 4.8,
    prepTimeMinutes: 35,
    servings: 4,
    calorie: 390,
    protein: 16,
    carbs: 42,
    fats: 17,
    instructions: [
      "Preheat the oven to 475°F (245°C).",
      "Roll out the pizza dough on a floured surface.",
      "Spread the pizza sauce evenly over the dough.",
      "Top with sliced mozzarella cheese.",
      "Bake for 12-15 minutes until the crust is golden.",
      "Garnish with fresh basil leaves and drizzle with olive oil before serving.",
    ],
  },
  {
    id: 9,
    name: "Tomato Basil Soup",
    thumbnail: "https://images.unsplash.com/photo-1629978444632-9f63ba0eff47",
    ingredients: [
      "6 tomatoes",
      "1 onion",
      "2 garlic cloves",
      "2 cups vegetable broth",
      "Fresh basil",
      "Olive oil",
      "Salt",
      "Pepper",
    ],
    tags: ["Soup", "Vegetarian", "Comfort Food"],
    shortDescription: "Smooth and creamy tomato soup with fresh basil.",
    rating: 4.6,
    prepTimeMinutes: 35,
    servings: 4,
    calorie: 170,
    protein: 4,
    carbs: 18,
    fats: 9,
    instructions: [
      "Cook onion and garlic.",
      "Add tomatoes and broth.",
      "Simmer for 20 minutes.",
      "Blend until smooth.",
      "Stir in basil and serve.",
    ],
  },
  {
    id: 10,
    name: "Banana Oat Smoothie",
    thumbnail: "https://images.unsplash.com/photo-1712056407284-c1eda76e7bcd",
    ingredients: [
      "2 bananas",
      "1 cup oats",
      "2 cups milk",
      "1 tbsp peanut butter",
      "1 tsp honey",
      "Ice cubes",
    ],
    tags: ["Breakfast", "Drink", "Healthy", "High Fiber"],
    shortDescription: "A filling smoothie packed with oats and bananas.",
    rating: 4.7,
    prepTimeMinutes: 5,
    servings: 2,
    calorie: 340,
    protein: 11,
    carbs: 49,
    fats: 11,
    instructions: [
      "Add all ingredients to a blender.",
      "Blend until smooth.",
      "Serve immediately.",
    ],
  },
];

async function seed() {
  await sql`    
        CREATE TABLE recipes (
            id SERIAL PRIMARY KEY,
            name TEXT NOT NULL,
            ingredients JSONB NOT NULL,
            tags JSONB NOT NULL,
            short_description TEXT,
            rating DECIMAL(2,1),
            prep_time_minutes INTEGER,
            servings INTEGER,
            calorie INTEGER,
            protein INTEGER,
            carbs INTEGER,
            fats INTEGER,
            thumbnail TEXT,
            instructions JSONB NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `;

  for (const item of RECIPES) {
    await sql`
    INSERT INTO recipes (
      id,
      name,
      ingredients,
      tags,
      short_description,
      rating,
      prep_time_minutes,
      servings,
      calorie,
      protein,
      carbs,
      fats,
      thumbnail,
      instructions
    )
    VALUES (
      ${item.id},
      ${item.name},
      ${JSON.stringify(item.ingredients)},
      ${JSON.stringify(item.tags)},
      ${item.shortDescription},
      ${item.rating},
      ${item.prepTimeMinutes},
      ${item.servings},
      ${item.calorie},
      ${item.protein},
      ${item.carbs},
      ${item.fats},
      ${item.thumbnail},
      ${JSON.stringify(item.instructions)}
    )
  `;
  }

  console.log(`Seed complete inserted ${RECIPES.length}`);
}

seed().catch((error) => {
  console.log("Seed failed", error);
  process.exit(1);
});
